language: r
cache: packages
r_github_packages:
  - jimhester/covr
  - trestletech/plumber
after_success:
  - Rscript -e 'library(covr);codecov()'
after_failure:
  - ./travis-tool.sh dump_logs
r_packages:
  - httpuv
  - R6
  - stringi
  - jsonlite
warnings_are_errors: true
